import sys, os
path = os.path.join(os.path.dirname(__file__), '../../')
sys.path.append(path)

import Shogi24Lib
from bs4 import BeautifulSoup

testLogin = Shogi24Lib.login()
searchUser = Shogi24Lib.searchUser(testLogin.doLogin())
#searchUser.search("nonbiriya")
searchResult = searchUser.getSearchResult("nonbiriya")
#print(searchResult.content)
soup = BeautifulSoup(searchResult.content, "html.parser")
#print(soup)
searchResultTable = searchUser.findTableTag(soup)
#print(searchResultTable)
members = searchUser.findTrTags(searchResultTable)
#print(members)
searchUser.getMembers(members)
tests = searchUser.getMemberSearchResultList()
#for test in tests:
#    print(test.getUserName())
#    print(test.getUserId())
#    print(test.getDanKyu())
#    print(test.getR())
#    print(test.getWinRate())
#    print(test.getWin())
#    print(test.getLose())
#    print(test.getDrow())
#    print(test.getBattle())
#    print(test.getMaxR())
#    print(test.getResion())
#    print(test.getProf())

test = searchUser.match("nonbiriya")
print(test.getUserName())
print(test.getUserId())
print(test.getDanKyu())
print(test.getR())
print(test.getWinRate())
print(test.getWin())
print(test.getLose())
print(test.getDrow())
print(test.getBattle())
print(test.getMaxR())
print(test.getResion())
print(test.getProf())

print(searchUser.getMatchId("nonbiriya"))